/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrototypeRouteImport } from './routes/prototype'

const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/prototype': typeof PrototypeRoute
}
export interface FileRoutesByTo {
  '/prototype': typeof PrototypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/prototype': typeof PrototypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/prototype'
  fileRoutesByTo: FileRoutesByTo
  to: '/prototype'
  id: '__root__' | '/prototype'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrototypeRoute: typeof PrototypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrototypeRoute: PrototypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
